### ISSUE TITLE
Install shipped CA file if none is found

### ISSUE THREAD

**Issue by webmozart** [padraic/file_get_contents#8]
The Composer installer installs its own CA file if none is found. Could this be a solution for the "A valid cafile could not be located locally" errors that occur frequently on different systems?

see

https://ci.appveyor.com/project/webmozart/cli/build/1.0.138
https://github.com/puli/issues/issues/163

**Comment by padraic** [comment]
It could if used as a final resort and monitored. The downside is that I am not in business of monitoring certs for compliance, i.e. any included CA file may fall out of date and include invalid/compromised certs - they do change over time. This bumps up the risk to the end user. For example, if one were to survey PHP packages online which include such a cert pack, I'd wager you'd find at least some which haven't been updated for a while...

I'll have a think about what might make a good "addCaCertsOfFinalResort()" solution.

**Comment by webmozart** [comment]
Thanks @padraic! Looking forward to a solution. :)

**Comment by ArnaudLigny** [comment]
Hi guys, any news about this issue? :-)

Note: the fork (#9) from @thewilkybarkid fixed my problem.
